'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('jobs', [{
      title: 'Manager at Stark Industries',
      type: 'Management',
      description: 'We need responsible manager for the main position in stark industries, because Pepper Potts do not want this job any more and Tony has no time for administrative work, he has to save the world.',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'IT Specialist at Stark Industries',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Hygenist',
      type: 'Hygen',
      description: 'In stark we need clear and calm office and we give good salary for the person who will help us with this',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Project manager at stark industries',
      type: 'IT',
      description: 'Project manage awesome things, we need better software for our office and we need someone to integrate Jarvis here.',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Accounter',
      type: 'Finances',
      description: 'We need responsible person for our accounting because the taxes are very high and we do not want to pay them all !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'C# senior developer',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS Junior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS Senior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS+angular Junior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS - MEAN STACK Junior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('jobs', [{
      title: 'Manager at Stark Industries',
      type: 'Management',
      description: 'We need responsible manager for the main position in stark industries, because Pepper Potts do not want this job any more and Tony has no time for administrative work, he has to save the world.',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'IT Specialist at Stark Industries',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Hygenist',
      type: 'Hygen',
      description: 'In stark we need clear and calm office and we give good salary for the person who will help us with this',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Project manager at stark industries',
      type: 'IT',
      description: 'Project manage awesome things, we need better software for our office and we need someone to integrate Jarvis here.',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Accounter',
      type: 'Finances',
      description: 'We need responsible person for our accounting because the taxes are very high and we do not want to pay them all !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'C# senior developer',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS Junior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS Senior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS+angular Junior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Full-stack JS - MEAN STACK Junior',
      type: 'Developement',
      description: 'DEVELOP SOME STRANGE THINGS, update Jarvis. You need to be GOD OF PROGRAMMING, because Tony need help with the new version of Jarvis and Dummy !!!',
      status: 'active',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },
};
